name: "Validate Gradle Wrapper"

on:
  workflow_dispatch: null
  push:
    paths:
      - "gradlew"
      - "gradlew.bat"
      - "gradle/wrapper/"
  pull_request:
    paths:
      - "gradlew"
      - "gradlew.bat"
      - "gradle/wrapper/"

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
