---
name: "publish a release"

on:
  workflow_dispatch:
    inputs:
      force_version:
        description: "Force version number to publish (empty for automatic semver versioning)"
        required: false
        default: ""
      to_publish: #TODO
        description: "What to publish"
        required: true
        default: "all"
        type: choice
        options:
          - plugin-gradle
          - plugin-maven
          - all
          - lib

permissions:
  contents: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  nativeCompile:
    name: "${{ matrix.platform.name }}: create production-binary"
    strategy:
      matrix:
        platform:
          - name: "linux-x86_64"
            runner: "ubuntu-latest"
          - name: "linux-aarch64"
            runner: "ubuntu-24.04-arm"
          - name: "windows-x86_64"
            runner: "windows-latest"
          - name: "macos-aaarch64"
            runner: "macos-latest"
          - name: "macos-x86_64"
            runner: "macos-13"
    runs-on: "${{ matrix.platform.runner }}"
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: "15"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - name: "Install JDK 21"
        uses: "actions/setup-java@v4"
        with:
          distribution: "graalvm"
          java-version: 21
      - name: "Install Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "lts/jod" # 22
      - name: "Setup Gradle"
        uses: "gradle/actions/setup-gradle@v4"
      - name: "Run nativeCompile"
        run: "./gradlew -Prelease=true nativeCompile"
      - name: "upload binary" # for collecting later
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.RUN_UNIQUE_ID }}-native-binary-${{ matrix.platform.name }}"
          path: app/build/native/nativeCompile/spotless
          retention-days: 1
          if-no-files-found: "error"
  createRelease:
    needs: nativeCompile
    name: "Create a new release"
    runs-on: ubuntu-latest
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: "15"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Install JDK 21"
        uses: "actions/setup-java@v4"
        with:
          distribution: "graalvm"
          java-version: 21
      - name: "Setup Gradle"
        uses: "gradle/actions/setup-gradle@v4"
      - name: "Retrieve production-binaries"
        uses: "actions/download-artifact@v4"
        with:
          # no name - download all artifacts
          path: "app/build/collected-binaries"
      - name: Display structure of downloaded files
        run: "ls -R app/build/collected-binaries"
